version: '3.8'

services:

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      - HOST=dpg-cnavkhicn0vc73927efg-a.oregon-postgres.render.com
      - POSTGRES_DB=qonaqol
      - POSTGRES_USER=ilqar
      - POSTGRES_PASSWORD=YI09u9Z2NMQhEAqTMFR0oU0WuDBhcWc0
    ports:
      - "5432:5432"

  qonaq-ol:
    build:
      context: .
    image: ilgarmustafayev22/qonaqol:v1

    container_name: qonaq-ol
    environment:
      - HOST=postgres2
    ports:
      - "8081:8081"
    depends_on:
      - postgres2