server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://localhost:5432/qonaqol"
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework.security: trace

minio:
  url: http://localhost:9000
  accessKey: VpAtKSxzqKBjNi4g7k9P
  secretKey: Bnxey32cHcJiGL9eVQdgJTF95Vsr1VqxPMoHdo2z
  bucketName: qonaq-ol
  defaultFolder: /

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui